### ISSUE TITLE
How to import this Project into eclipse

### ISSUE THREAD

**Issue by VinayTShetty** [aurasphere/notabat#1]
Thanks for Providing the snippet of code..

The Jar file is not Running when Double clicked.
Tried with Command window also but its not responding.
Can u please tell how to import this project to eclipse...?
It will be helpfull

Thanks in advnace..

**Comment by aurasphere** [comment]
Hey @VinayTShetty! 
Sorry for the late answer but I've apparently missed the notification.

To import this project, right click anywhere on the project view and select Import... > Existing Maven project and then follow the wizard.

Also, are you sure the app is not running? When you open it, nothing is supposed to happen until your battery goes below the power threshold. If you want to check whether the program is running or not, you can open the task manager and check if another Java Runtime process has been added on the process list.

Let me know if you need anything else!
