### ISSUE TITLE
Is this made for Windows 7?

### ISSUE THREAD

**Issue by DavidUgoOmenukwa** [aurasphere/notabat#2]
Thank you for this code, I'm looking forwards to trying it out. However, I need to know if this code is made for Windows 7. Thanks!

**Comment by aurasphere** [comment]
Hey @DavidUgoOmenukwa yes this code was made specifically for Windows 7 and tested on it!

**Comment by DavidUgoOmenukwa** [comment]
Ok, thank you for replying so fast!

**Comment by DavidUgoOmenukwa** [comment]
Just two more questions: One, if you leave the laptop charging past your threshold (let's say 98%), would you continue to receive notifications every n minutes? Two, do the popups make any sound or can you set that yourself?

**Comment by aurasphere** [comment]
There are 2 threshold. If you are referring to the full battery, then yes, you will receive notifications every n minutes until you plug the charger off. Same goes for the low battery, when you drop down the given threshold you get notifications until you plug the charger in. You can set for each one your own sound (even different) or leave it without, in the configuration file. Let me know if you have any more questions!

**Comment by DavidUgoOmenukwa** [comment]
Yes, I tried to run it-- downloaded the entire project ZIP, extracted it into its own folder in Downloads, and tried to run start_notabat. However, Windows said something about registry keys. Is something wrong with my procedure or computer?
